#开发环境配置
server:
  #端口
  port: 8880
  tomcat:
    uri-encoding: utf-8
#日志配置
logging:
  level:
    com.yj.oa.project.mapper: debug
#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
     cache: false


# MyBatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.yj.oa.project.po
  configuration:
    map-underscore-to-camel-case: true








